# Caricamento modulo FastCGI
LoadModule fcgid_module modules/mod_fcgid.so

# Configurazione per usare PHP via FastCGI
<IfModule fcgid_module>
    AddHandler fcgid-script .php
    FcgidInitialEnv PHPRC "C:/php"
    FcgidWrapper "C:/php/php-cgi.exe" .php

    <FilesMatch "\.php$">
        SetHandler fcgid-script
    </FilesMatch>
</IfModule>

<IfModule mime_module>
    AddType text/html .php .phps
</IfModule>

# Alias di sistema (licenze, phpmyadmin, webalizer)
<IfModule fcgid_module>
  Alias /licenses "C:/xampp/licenses/"
    <Directory "C:/xampp/licenses">
        Options +Indexes
        <IfModule autoindex_color_module>
            DirectoryIndexTextColor  "#000000"
            DirectoryIndexBGColor "#f8e8a0"
            DirectoryIndexLinkColor "#bb3902"
            DirectoryIndexVLinkColor "#bb3902"
            DirectoryIndexALinkColor "#bb3902"
        </IfModule>
        Require local
        ErrorDocument 403 /error/XAMPP_FORBIDDEN.html.var
   </Directory>

    Alias /phpmyadmin "C:/xampp/phpMyAdmin/"
    <Directory "C:/xampp/phpmyadmin">
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
    </Directory>

    Alias /webalizer "C:/xampp/webalizer/"
    <Directory "C:/xampp/webalizer">
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
    </Directory>

</IfModule>